@startuml
' TP 1 : Borne de Recharge IRVE - BTS CIEL
left to right direction
skinparam packageStyle rectangle

actor "Conducteur" as User
actor "Technicien de maintenance" as Tech
actor "Serveur Cloud OCPP" as Cloud <<Système externe>>

rectangle "Borne de Recharge IRVE" {
    usecase "Démarrer une session de charge" as UC_Charge
    usecase "Arrêter la session de charge" as UC_Stop
    usecase "S'authentifier par badge RFID" as UC_Auth
    usecase "Consulter les mesures en direct" as UC_Mesures
    usecase "Recevoir un reçu par email" as UC_Recu
    usecase "Lancer l'autodiagnostic matériel" as UC_Diag
    usecase "Mettre à jour le firmware" as UC_Update
    usecase "Arrêter la borne à distance" as UC_Urgence
}

' ==============================================================================
' LIAISONS EXISTANTES DÉJÀ FOURNIES :
' ==============================================================================
User --> UC_Charge
User --> UC_Stop
User --> UC_Mesures

Tech --> UC_Diag
Tech --> UC_Update

Cloud --> UC_Urgence

' ==============================================================================
' TODO 1 : Généralisation (Héritage) entre Acteurs
' Le Technicien est un Conducteur avec des privilèges supplémentaires.
' Syntaxe d'héritage : ActeurFils --|> ActeurParent
' ------------------------------------------------------------------------------
' Écrivez ci-dessous la relation d'héritage entre Tech et User :


' ==============================================================================
' TODO 2 : Dépendance obligatoire <<include>>
' Pour "Démarrer une session de charge" (UC_Charge), l'usager doit TOUJOURS
' obligatoirement "S'authentifier par badge RFID" (UC_Auth).
' Syntaxe : CasSource ..> CasObligatoire : <<include>>
' ------------------------------------------------------------------------------
' Écrivez ci-dessous l'inclusion entre UC_Charge et UC_Auth :


' ==============================================================================
' TODO 3 : Dépendance optionnelle <<extend>>
' Après avoir chargé (UC_Charge), le système propose l'option facultative
' "Recevoir un reçu par email" (UC_Recu).
' Syntaxe : CasBase <.. CasOptionnel : <<extend>>
' ------------------------------------------------------------------------------
' Écrivez ci-dessous l'extension entre UC_Charge et UC_Recu :


@enduml

